const axios = require("axios");
const handleBreeds = require("./dogs");
jest.mock("axios");

const arrayOfBreeds = [
  " affenpinscher",
  " african",
  " airedale",
  " akita",
  " appenzeller",
  "shepherd australian",
  " basenji",
  " beagle",
  " bluetick",
  " borzoi",
  " bouvier",
  " boxer",
  " brabancon",
  " briard",
  "norwegian buhund",
  "boston english french bulldog",
  "staffordshire bullterrier",
  "australian cattledog",
  " chihuahua",
  " chow",
  " clumber",
  " cockapoo",
  "border collie",
  " coonhound",
  "cardigan corgi",
  " cotondetulear",
  " dachshund",
  " dalmatian",
  "great dane",
  "scottish deerhound",
  " dhole",
  " dingo",
  " doberman",
  "norwegian elkhound",
  " entlebucher",
  " eskimo",
  "lapphund finnish",
  "bichon frise",
  " germanshepherd",
  "italian greyhound",
  " groenendael",
  " havanese",
  "afghan basset blood english ibizan plott walker hound",
  " husky",
  " keeshond",
  " kelpie",
  " komondor",
  " kuvasz",
  " labradoodle",
  " labrador",
  " leonberg",
  " lhasa",
  " malamute",
  " malinois",
  " maltese",
  "bull english tibetan mastiff",
  " mexicanhairless",
  " mix",
  "bernese swiss mountain",
  " newfoundland",
  " otterhound",
  "caucasian ovcharka",
  " papillon",
  " pekinese",
  " pembroke",
  "miniature pinscher",
  " pitbull",
  "german germanlonghair pointer",
  " pomeranian",
  "miniature standard toy poodle",
  " pug",
  " puggle",
  " pyrenees",
  " redbone",
  "chesapeake curly flatcoated golden retriever",
  "rhodesian ridgeback",
  " rottweiler",
  " saluki",
  " samoyed",
  " schipperke",
  "giant miniature schnauzer",
  "english gordon irish setter",
  "english shetland sheepdog",
  " shiba",
  " shihtzu",
  "blenheim brittany cocker irish japanese sussex welsh spaniel",
  "english springer",
  " stbernard",
  "american australian bedlington border cairn dandie fox irish kerryblue lakeland norfolk norwich patterdale russell scottish sealyham silky tibetan toy westhighland wheaten yorkshire terrier",
  " vizsla",
  "spanish waterdog",
  " weimaraner",
  " whippet",
  "irish wolfhound",
];

const axiosResponse = {
  data: {
    message: {
      affenpinscher: [],
      african: [],
      airedale: [],
      akita: [],
      appenzeller: [],
      australian: ["shepherd"],
      basenji: [],
      beagle: [],
      bluetick: [],
      borzoi: [],
      bouvier: [],
      boxer: [],
      brabancon: [],
      briard: [],
      buhund: ["norwegian"],
      bulldog: ["boston", "english", "french"],
      bullterrier: ["staffordshire"],
      cattledog: ["australian"],
      chihuahua: [],
      chow: [],
      clumber: [],
      cockapoo: [],
      collie: ["border"],
      coonhound: [],
      corgi: ["cardigan"],
      cotondetulear: [],
      dachshund: [],
      dalmatian: [],
      dane: ["great"],
      deerhound: ["scottish"],
      dhole: [],
      dingo: [],
      doberman: [],
      elkhound: ["norwegian"],
      entlebucher: [],
      eskimo: [],
      finnish: ["lapphund"],
      frise: ["bichon"],
      germanshepherd: [],
      greyhound: ["italian"],
      groenendael: [],
      havanese: [],
      hound: [
        "afghan",
        "basset",
        "blood",
        "english",
        "ibizan",
        "plott",
        "walker",
      ],
      husky: [],
      keeshond: [],
      kelpie: [],
      komondor: [],
      kuvasz: [],
      labradoodle: [],
      labrador: [],
      leonberg: [],
      lhasa: [],
      malamute: [],
      malinois: [],
      maltese: [],
      mastiff: ["bull", "english", "tibetan"],
      mexicanhairless: [],
      mix: [],
      mountain: ["bernese", "swiss"],
      newfoundland: [],
      otterhound: [],
      ovcharka: ["caucasian"],
      papillon: [],
      pekinese: [],
      pembroke: [],
      pinscher: ["miniature"],
      pitbull: [],
      pointer: ["german", "germanlonghair"],
      pomeranian: [],
      poodle: ["miniature", "standard", "toy"],
      pug: [],
      puggle: [],
      pyrenees: [],
      redbone: [],
      retriever: ["chesapeake", "curly", "flatcoated", "golden"],
      ridgeback: ["rhodesian"],
      rottweiler: [],
      saluki: [],
      samoyed: [],
      schipperke: [],
      schnauzer: ["giant", "miniature"],
      setter: ["english", "gordon", "irish"],
      sheepdog: ["english", "shetland"],
      shiba: [],
      shihtzu: [],
      spaniel: [
        "blenheim",
        "brittany",
        "cocker",
        "irish",
        "japanese",
        "sussex",
        "welsh",
      ],
      springer: ["english"],
      stbernard: [],
      terrier: [
        "american",
        "australian",
        "bedlington",
        "border",
        "cairn",
        "dandie",
        "fox",
        "irish",
        "kerryblue",
        "lakeland",
        "norfolk",
        "norwich",
        "patterdale",
        "russell",
        "scottish",
        "sealyham",
        "silky",
        "tibetan",
        "toy",
        "westhighland",
        "wheaten",
        "yorkshire",
      ],
      vizsla: [],
      waterdog: ["spanish"],
      weimaraner: [],
      whippet: [],
      wolfhound: ["irish"],
    },
    status: "success",
  },
};

it("returns array of subbreeds and breeds", async () => {
  axios.get.mockResolvedValue(axiosResponse);
  const breeds = await handleBreeds();
  expect(breeds).toEqual({ message: arrayOfBreeds, status: "success" });
});
